kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: library
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: ""