apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: library-reader-service
  name: library-reader-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-reader-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: library-reader-service
    spec:
      containers:
      - image: ((REGISTRY))/library-reader:1.0.0
        name: book
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: postgresql-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: postgresql-password
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: library-reader-service
  name: library-reader-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: library-reader-service
  type: ClusterIP
status:
  loadBalancer: {}
